import { FaRegFolder } from "react-icons/fa";
import { FaCircle, FaRegCircle, FaRegFolderOpen } from "react-icons/fa6";
import { IoGrid, IoGridOutline } from "react-icons/io5";
import { PiRoadHorizonFill, PiRoadHorizonLight } from "react-icons/pi";

export const MENU_DATA = [
    {
        url:'/dashboard',
        label:'Dashboard',
        icon: <IoGridOutline className="text-xl"/>,
        iconActive: <IoGrid className="text-xl"/>
    },
    {
        url:'',
        label:'Laporan',
        icon: <FaRegFolder className="text-xl"/>,
        iconActive: <FaRegFolderOpen className="text-xl"/>,
        subMenu:[
            {
                url: '/report/daily',
                icon: <FaRegCircle className="text-xl"/>,
                iconActive: <FaCircle className="text-xl"/>,
                label: 'Laporan Per Hari'
            },
        ]
    },
    {
        url:'/gate',
        label:'master Gerbang',
        icon: <PiRoadHorizonLight className="text-xl"/>,
        iconActive: <PiRoadHorizonFill className="text-xl"/>
    },
]

export const RUAS_DATA = [
    { id: 1, nama: "Ruas 1" },
    { id: 2, nama: "Ruas 2" },
    { id: 3, nama: "Ruas 1" },
    { id: 4, nama: "Ruas 1" },
    { id: 5, nama: "Ruas 2" },
    { id: 6, nama: "Ruas 2" },
    { id: 7, nama: "Ruas 1" },
    { id: 8, nama: "Ruas 1" },
    { id: 9, nama: "Ruas 2" },
    { id: 10, nama: "Ruas 2" },
    { id: 11, nama: "Ruas 1" },
    { id: 12, nama: "Ruas 1" },
    { id: 13, nama: "Ruas 1" },
    { id: 14, nama: "Ruas 2" },
    { id: 15, nama: "Ruas 2" },
    { id: 16, nama: "Ruas 1" },
    { id: 17, nama: "Ruas 1" },
    { id: 18, nama: "Ruas 2" },
    { id: 19, nama: "Ruas 2" },
    { id: 20, nama: "Ruas 1" },
    { id: 21, nama: "Ruas 1" },
    { id: 22, nama: "Ruas 1" },
    { id: 23, nama: "Ruas 2" }
]

export const GERBANG_DATA = [
    { id: 1, nama: "Cikarang Utama" },
    { id: 2, nama: "Pasuruan Timur" },
    { id: 3, nama: "Cikampek Barat" },
    { id: 4, nama: "Purwakarta Utama" },
    { id: 5, nama: "Mojokerto Timur" },
    { id: 6, nama: "Tangerang Selatan" },
    { id: 7, nama: "Brebes Timur" },
    { id: 8, nama: "Cirebon Utara" },
    { id: 9, nama: "Malang Utara" },
    { id: 10, nama: "Garut Selatan" },
]

export const GARDU_DATA = [
    { id: 1, nama: "01" },
    { id: 2, nama: "02" },
    { id: 3, nama: "03" },
    { id: 4, nama: "04" },
    { id: 5, nama: "05" },
    { id: 6, nama: "06" },
    { id: 7, nama: "07" },
    { id: 8, nama: "08" },
    { id: 9, nama: "09" },
    { id: 10, nama: "10" },
]
export const LALIN_DATA = [
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Cikarang Utama",
        gardu: "01",
        hari: "Sabtu",
        tanggal: "2024-01-06",
        metode_pembayaran: "fio",
        gol_1: 250,
        gol_2: 380,
        gol_3: 320,
        gol_4: 450,
        gol_5: 120,
        total_lalin: 1520,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Cikarang Utama",
        gardu: "02",
        hari: "Senin",
        tanggal: "2024-02-15",
        metode_pembayaran: "Tunai",
        gol_1: 200,
        gol_2: 350,
        gol_3: 280,
        gol_4: 420,
        gol_5: 150,
        total_lalin: 1400,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Pasuruan Timur",
        gardu: "03",
        hari: "Rabu",
        tanggal: "2024-03-21",
        metode_pembayaran: "E-toll",
        gol_1: 180,
        gol_2: 300,
        gol_3: 240,
        gol_4: 380,
        gol_5: 100,
        total_lalin: 1200,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Cikampek Barat",
        gardu: "04",
        hari: "Kamis",
        tanggal: "2024-04-10",
        metode_pembayaran: "fio",
        gol_1: 220,
        gol_2: 360,
        gol_3: 300,
        gol_4: 430,
        gol_5: 110,
        total_lalin: 1420,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Purwakarta Utama",
        gardu: "05",
        hari: "Jumat",
        tanggal: "2024-05-05",
        metode_pembayaran: "Tunai",
        gol_1: 240,
        gol_2: 370,
        gol_3: 310,
        gol_4: 440,
        gol_5: 130,
        total_lalin: 1490,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Mojokerto Timur",
        gardu: "06",
        hari: "Sabtu",
        tanggal: "2024-06-12",
        metode_pembayaran: "E-toll",
        gol_1: 260,
        gol_2: 390,
        gol_3: 330,
        gol_4: 460,
        gol_5: 140,
        total_lalin: 1580,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Tangerang Selatan",
        gardu: "07",
        hari: "Minggu",
        tanggal: "2024-07-18",
        metode_pembayaran: "ktp",
        gol_1: 270,
        gol_2: 400,
        gol_3: 340,
        gol_4: 470,
        gol_5: 150,
        total_lalin: 1630,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Brebes Timur",
        gardu: "08",
        hari: "Senin",
        tanggal: "2024-08-29",
        metode_pembayaran: "Tunai",
        gol_1: 280,
        gol_2: 410,
        gol_3: 350,
        gol_4: 480,
        gol_5: 160,
        total_lalin: 1680,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Cirebon Utara",
        gardu: "04",
        hari: "Selasa",
        tanggal: "2024-09-14",
        metode_pembayaran: "E-toll",
        gol_1: 290,
        gol_2: 420,
        gol_3: 360,
        gol_4: 490,
        gol_5: 170,
        total_lalin: 1730,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Malang Utara",
        gardu: "09",
        hari: "Rabu",
        tanggal: "2024-10-20",
        metode_pembayaran: "fio",
        gol_1: 300,
        gol_2: 430,
        gol_3: 370,
        gol_4: 500,
        gol_5: 180,
        total_lalin: 1780,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Garut Selatan",
        gardu: "01",
        hari: "Kamis",
        tanggal: "2024-11-08",
        metode_pembayaran: "Tunai",
        gol_1: 310,
        gol_2: 440,
        gol_3: 380,
        gol_4: 510,
        gol_5: 190,
        total_lalin: 1830,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Serang Timur",
        gardu: "05",
        hari: "Jumat",
        tanggal: "2024-12-16",
        metode_pembayaran: "E-toll",
        gol_1: 320,
        gol_2: 450,
        gol_3: 390,
        gol_4: 520,
        gol_5: 200,
        total_lalin: 1880,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Jogja Utara",
        gardu: "07",
        hari: "Sabtu",
        tanggal: "2025-01-03",
        metode_pembayaran: "fio",
        gol_1: 330,
        gol_2: 460,
        gol_3: 400,
        gol_4: 530,
        gol_5: 210,
        total_lalin: 1930,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Padalarang Timur",
        gardu: "04",
        hari: "Minggu",
        tanggal: "2025-02-21",
        metode_pembayaran: "Tunai",
        gol_1: 340,
        gol_2: 470,
        gol_3: 410,
        gol_4: 540,
        gol_5: 220,
        total_lalin: 1980,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Sidoarjo Timur",
        gardu: "10",
        hari: "Senin",
        tanggal: "2025-03-10",
        metode_pembayaran: "E-toll",
        gol_1: 350,
        gol_2: 480,
        gol_3: 420,
        gol_4: 550,
        gol_5: 230,
        total_lalin: 2030,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Sukabumi Utara",
        gardu: "03",
        hari: "Selasa",
        tanggal: "2025-04-25",
        metode_pembayaran: "fio",
        gol_1: 360,
        gol_2: 490,
        gol_3: 430,
        gol_4: 560,
        gol_5: 240,
        total_lalin: 2080,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Bogor Selatan",
        gardu: "05",
        hari: "Rabu",
        tanggal: "2025-05-19",
        metode_pembayaran: "Tunai",
        gol_1: 370,
        gol_2: 500,
        gol_3: 440,
        gol_4: 570,
        gol_5: 250,
        total_lalin: 2130,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Solo Barat",
        gardu: "02",
        hari: "Kamis",
        tanggal: "2025-06-14",
        metode_pembayaran: "E-toll",
        gol_1: 380,
        gol_2: 510,
        gol_3: 450,
        gol_4: 580,
        gol_5: 260,
        total_lalin: 2180,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Cikampek Timur",
        gardu: "09",
        hari: "Jumat",
        tanggal: "2025-07-03",
        metode_pembayaran: "fio",
        gol_1: 390,
        gol_2: 520,
        gol_3: 460,
        gol_4: 590,
        gol_5: 270,
        total_lalin: 2230,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Banyuwangi Barat",
        gardu: "06",
        hari: "Sabtu",
        tanggal: "2025-08-21",
        metode_pembayaran: "Tunai",
        gol_1: 400,
        gol_2: 530,
        gol_3: 470,
        gol_4: 600,
        gol_5: 280,
        total_lalin: 2280,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Cirebon Selatan",
        gardu: "02",
        hari: "Minggu",
        tanggal: "2025-09-09",
        metode_pembayaran: "E-toll",
        gol_1: 410,
        gol_2: 540,
        gol_3: 480,
        gol_4: 610,
        gol_5: 290,
        total_lalin: 2330,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Waru Barat",
        gardu: "10",
        hari: "Senin",
        tanggal: "2025-10-28",
        metode_pembayaran: "fio",
        gol_1: 420,
        gol_2: 550,
        gol_3: 490,
        gol_4: 620,
        gol_5: 300,
        total_lalin: 2380,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Magelang Timur",
        gardu: "10",
        hari: "Selasa",
        tanggal: "2025-11-15",
        metode_pembayaran: "Tunai",
        gol_1: 430,
        gol_2: 560,
        gol_3: 500,
        gol_4: 630,
        gol_5: 310,
        total_lalin: 2430,
    },
    {
        ruas_nama: "Ruas 1",
        gerbang_nama: "Padalarang Barat",
        gardu: "03",
        hari: "Rabu",
        tanggal: "2025-12-22",
        metode_pembayaran: "E-toll",
        gol_1: 440,
        gol_2: 570,
        gol_3: 510,
        gol_4: 640,
        gol_5: 320,
        total_lalin: 2480,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Malang Selatan",
        gardu: "05",
        hari: "Kamis",
        tanggal: "2026-01-11",
        metode_pembayaran: "fio",
        gol_1: 450,
        gol_2: 580,
        gol_3: 520,
        gol_4: 650,
        gol_5: 330,
        total_lalin: 2530,
    },
    {
        ruas_nama: "Ruas 2",
        gerbang_nama: "Garut Utara",
        gardu: "01",
        hari: "Jumat",
        tanggal: "2026-02-28",
        metode_pembayaran: "Tunai",
        gol_1: 460,
        gol_2: 590,
        gol_3: 530,
        gol_4: 660,
        gol_5: 340,
        total_lalin: 2580,
    },
]