import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { AppProvider } from "@/context/useAppContext";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
        <body className={`relative ${inter.className}`}>
          <AppProvider>
              <main className="bg-slate-100 hidden md:flex">
                <Sidebar/>
                <div className="grow">
                  <Navbar/>
                  <div className="p-5">
                    {children}
                  </div>
                </div>
                <Toaster/>
              </main>
              <div className="absolute top-0 w-full text-center h-screen bg-gray-800 flex items-center md:hidden justify-center text-white">
                Sorry, this view does not yet support mobile devices.
              </div>
          </AppProvider>
        </body>
      </html>
  );
}
